pr: ["master"]

jobs:
  - job:
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .ci/install-rust.yml
        parameters:
          rust_version: stable
      - bash: |
          export RUST_BACKTRACE=1
          cargo check --all || exit
          cargo test --all || exit
        displayName: Run cargo check and test 
