[package]
name = "gloo-console-timer"
version = "0.1.0"
authors = ["Rust and WebAssembly Working Group"]
edition = "2018"

[dependencies.web-sys]
version = "0.3.14"
features = [
    "console",
]

[dev-dependencies]
wasm-bindgen-test = "0.2.37"